# Generated by Django 4.1.9 on 2023-05-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroContacto', models.CharField(max_length=100)),
                ('direcciondeContacto', models.CharField(max_length=100)),
                ('personalEncargado', models.CharField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
                ('fechaCierre', models.DateField()),
                ('cantidadEmisionesGases', models.FloatField()),
                ('objetivosMetasALlegar', models.CharField(max_length=5000)),
                ('actividadesProcesosAImplementar', models.CharField(max_length=5000)),
                ('presupuesto', models.FloatField()),
                ('seguimientos', models.CharField(max_length=5000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='PQRSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField()),
                ('fechaCierre', models.DateField()),
                ('numeroContacto', models.CharField(max_length=100)),
                ('tipoPQRSF', models.CharField(max_length=100)),
                ('detallesPQRSF', models.CharField(max_length=5000)),
                ('evaluacionExperiencia', models.IntegerField()),
                ('causaRaizPQRSF', models.CharField(max_length=5000)),
                ('accionesCorrectivas', models.CharField(max_length=5000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_entries', to='accounts.user')),
                ('personalEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.asesorias')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrsf_entries', to='accounts.user')),
            ],
        ),
    ]
