# Generated by Django 4.1.9 on 2023-05-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuellaDeCarbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumogasolina', models.FloatField()),
                ('consumodiesel', models.FloatField()),
                ('consumogasnaturalcomprimido', models.FloatField()),
                ('consumogasnaturallicuado', models.FloatField()),
                ('consumocarbonmineral', models.FloatField()),
                ('consumocarbonvegetal', models.FloatField()),
                ('ganadobovino', models.FloatField()),
                ('ganadoovino', models.FloatField()),
                ('ganadoporcino', models.FloatField()),
                ('avicola', models.FloatField()),
                ('consimoelectricidad', models.FloatField()),
                ('generacionnorenovablehidraulica', models.FloatField()),
                ('generacionnorenovablepetroloe', models.FloatField()),
                ('generacionnorenovablenuclear', models.FloatField()),
                ('consumopapel', models.FloatField()),
                ('consumomovil', models.FloatField()),
                ('consumocomputador', models.FloatField()),
                ('consumoplastico', models.FloatField()),
                ('consumotelevisor', models.FloatField()),
                ('consumolavadora', models.FloatField()),
                ('consumonevera', models.FloatField()),
                ('cochemotocicleta', models.FloatField()),
                ('cocheautmovilpequeño', models.FloatField()),
                ('cocheautmovilmediano', models.FloatField()),
                ('cocheautmovilgrande', models.FloatField()),
                ('cocheautmovildeportivo', models.FloatField()),
                ('cochesuvpequeño', models.FloatField()),
                ('cochesuvmediano', models.FloatField()),
                ('cochesuvgrande', models.FloatField()),
                ('cochesuvdeportivo', models.FloatField()),
                ('avion', models.FloatField()),
                ('tren', models.FloatField()),
                ('alimentacionres', models.FloatField()),
                ('alimentacioncerdo', models.FloatField()),
                ('alimentacionpollo', models.FloatField()),
                ('alimentacionpescado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionsugerencias', models.CharField(max_length=5000)),
                ('cantidadsugerencias', models.PositiveSmallIntegerField(null=True)),
                ('asesorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.asesorias')),
                ('huelladecarbonoR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.huelladecarbono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='huelladecarbono',
            name='descripcionsugerencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.retroalimentacion'),
        ),
        migrations.AddField(
            model_name='huelladecarbono',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
