# Generated by Django 4.1.7 on 2023-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="matchingLearningModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("architecture", models.FileField(upload_to="matchingLearningModels/")),
                ("weights", models.FileField(upload_to="matchingLearningModels/")),
                ("priority", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
