# Generated by Django 4.1.9 on 2023-05-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('numberOfImages', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='matchingLearningModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('architecture', models.FileField(upload_to='matchingLearningModels/')),
                ('weights', models.FileField(upload_to='matchingLearningModels/')),
                ('priority', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproceso', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=2000)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compania_entries', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('porcentajeCerteza', models.FloatField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artificialIntelligence.categoriaimagenes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Companias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompania', models.CharField(max_length=50)),
                ('direccioncompania', models.CharField(max_length=200)),
                ('materialesquereciclan', models.CharField(max_length=200)),
                ('cantidadmaterialesreciclados', models.FloatField()),
                ('certificados', models.CharField(max_length=2000)),
                ('tarifas', models.FloatField()),
                ('huelladecarbono', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculator.huelladecarbono')),
                ('metodosprocesos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artificialIntelligence.metodosprocesos')),
                ('retroalimentacion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculator.retroalimentacion')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
