from django import forms

class HuellaDeCarbonoForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(HuellaDeCarbonoForm, self).__init__(*args, **kwargs)
        self.fields['consumoGasolina'] =                forms.FloatField(label='Consumo de gasolina en litros', required=True)
        self.fields['consumoDiesel'] =                  forms.FloatField(label='Consumo de diesel en litros', required=True)
        self.fields['consumoGasNaturalComprimido'] =    forms.FloatField(label='Consumo de gas natural comprimido  en litros', required=True)
        self.fields['consumoGasNaturalLicuado'] =       forms.FloatField(label='Consumo de gas natural licuado en litros', required=True)
        self.fields['consumoCarbonMineral'] =           forms.FloatField(label='Consumo de carbon mineral en kilos', required=True)
        self.fields['consumoCarbonVegetal'] =           forms.FloatField(label='Consumo de carbon vegetal en kilos', required=True)
        self.fields['cantidadGanadoBovino'] =           forms.FloatField(label='Cantidad de ganado bovino por cada cabeza/año', required=True)
        self.fields['cantidadGanadoOvino'] =            forms.FloatField(label='Cantidad de ganado ovino por cada cabeza/año', required=True)
        self.fields['cantidadGanadoPorcino'] =          forms.FloatField(label='Cantidad de ganado porcino por cada cabeza/año', required=True)
        self.fields['cantidadAvicola'] =                forms.FloatField(label='Cantidad de avicola por cabeza/ciclo', required=True)
        self.fields['consumoElectricidad'] =            forms.FloatField(label='Consumo de electricidad por Kwh', required=True)
        self.fields['generacionElectricidadNoRenovableHidraulica'] =    forms.FloatField(label='Generación de electricidad no renovable a partir de hidraulica por Kwh', required=True)
        self.fields['generacionElectricidadNoRenovablePetroleo'] =      forms.FloatField(label='Generación de electricidad no renovable a partir de petroleo por Kwh', required=True)
        self.fields['generacionElectricidadNoRenovableNuclear'] =       forms.FloatField(label='Generación de electricidad no renovable a partir de nuclear por Kwh', required=True)
        self.fields['consumoPapel'] =                   forms.FloatField(label='Consumo de papel en kilos', required=True)
        self.fields['consumoMoviles'] =                 forms.FloatField(label='Consumo de moviles en unidades de pertenencia', required=True)
        self.fields['consumoPortatiles'] =              forms.FloatField(label='Consumo de portatiles en unidades de pertenencia', required=True)
        self.fields['consumoPlastico'] =                forms.FloatField(label='Consumo de plastico en unidades de pertenencia', required=True)
        self.fields['consumoTV'] =                      forms.FloatField(label='Consumo de TV en unidades de pertenencia', required=True)
        self.fields['consumoLavadora'] =                forms.FloatField(label='Consumo de lavadora en unidades de pertenencia', required=True)
        self.fields['consumoNevera'] =                  forms.FloatField(label='Consumo de nevera en unidades de pertenencia', required=True)
        self.fields['consumoMotocicleta'] =             forms.FloatField(label='Consumo de motocicletas por kilometro recorrido', required=True)
        self.fields['consumoAutomovilPequeno'] =        forms.FloatField(label='Consumo de coche pequeño por kilometro recorrido', required=True)   
        self.fields['consumoAutomovilMediano'] =        forms.FloatField(label='Consumo de coche mediano por kilometro recorrido', required=True)
        self.fields['consumoAutomovilGrande'] =         forms.FloatField(label='Consumo de coche grande por kilometro recorrido', required=True)
        self.fields['consumoAutomovilDeportivo'] =      forms.FloatField(label='Consumo de coche deportivo por kilometro recorrido', required=True)
        self.fields['consumoSUVPequeno'] =              forms.FloatField(label='Consumo de SUV pequeño por kilometro recorrido', required=True)
        self.fields['consumoSUVMediano'] =              forms.FloatField(label='Consumo de SUV mediano por kilometro recorrido', required=True)
        self.fields['consumoSUVGrande'] =               forms.FloatField(label='Consumo de SUV grande por kilometro recorrido', required=True)
        self.fields['consumoSUVDeportivo'] =            forms.FloatField(label='Consumo de SUV deportivo por kilometro recorrido', required=True)
        self.fields['consumoAvion'] =                   forms.FloatField(label='Consumo de avion por kilometro recorrido', required=True)
        self.fields['consumoTren'] =                    forms.FloatField(label='Consumo de tren por kilometro recorrido', required=True)
        self.fields['consumoRes'] =                     forms.FloatField(label='Consumo de res por kilos', required=True)
        self.fields['consumoCerdo'] =                   forms.FloatField(label='Consumo de cerdo por kilos', required=True)
        self.fields['consumoPollo'] =                   forms.FloatField(label='Consumo de pollo por kilos', required=True)
        self.fields['consumoPescado'] =                 forms.FloatField(label='Consumo de pescado por kilos', required=True)