from django import forms

class HuellaDeCarbonoForm(forms.Form):
    tablaHuella1= forms.FloatField(label='Id huella tabla 1', required=True)
    idUsuario = forms.FloatField(label='Id usuario', required=True)
    idRetroalimentacion= forms.FloatField(label='Id retroalimentación', required=True)
    idImagen= forms.FloatField(label='Id imagen', required=True)
    idCompania= forms.FloatField(label='Id compañia', required=True)
    consumoGasolina= forms.FloatField(label='Consumo de gasolina || en litros', required=True)
    consumoDiesel= forms.FloatField(label='Consumo de diesel || en litros', required=True)
    consumoGasNaturalComprimido= forms.FloatField(label='Consumo de gas natural comprimido || en litros', required=True)
    consumoGasNaturalLicuado= forms.FloatField(label='Consumo de gas natural licuado || en litros', required=True)
    consumoCarbonMineral= forms.FloatField(label='Consumo de carbon mineral || en kilos', required=True)
    consumoCarbonVegetal= forms.FloatField(label='Consumo de carbon vegetal || en kilos', required=True)
    consumoLenia= forms.FloatField(label='Consumo de lenia || en kilos', required=True)
    cantidadGanadoBovino= forms.FloatField(label='Cantidad de ganado bovino || por cabezas/año', required=True)
    cantidadGanadoOvino= forms.FloatField(label='Cantidad de ganado ovino || por cabezas/año', required=True)
    cantidadGanadoPorcino= forms.FloatField(label='Cantidad de ganado porcino || por cabezas/año', required=True)
    cantidadGanadoCaprino= forms.FloatField(label='Cantidad de ganado caprino || por cabezas/año', required=True)
    cantidadAvicola= forms.FloatField(label='Cantidad de avicola || por cabezas/ciclo', required=True)
    consumoElectricidad= forms.FloatField(label='Consumo de electricidad || por Kwh', required=True)
    generacionElectricidadRenovable= forms.FloatField(label='Generación de electricidad renovable || por Kwh', required=True)
    generacionElectricidadNoRenovableCarbon= forms.FloatField(label='Generación de electricidad no renovable a partir de carbon || por Kwh', required=True)
    generacionElectricidadNoRenovableHidraulica= forms.FloatField(label='Generación de electricidad no renovable a partir de hidraulica || por Kwh', required=True)
    generacionElectricidadNoRenovableGasNatural= forms.FloatField(label='Generación de electricidad no renovable a partir de gas natural || por Kwh', required=True)
    generacionElectricidadNoRenovablePetroleo= forms.FloatField(label='Generación de electricidad no renovable a partir de petroleo || por Kwh', required=True)
    generacionElectricidadNoRenovableNuclear= forms.FloatField(label='Generación de electricidad no renovable a partir de nuclear || por Kwh', required=True)
    consumoPapel= forms.FloatField(label='Consumo de papel || en kilos', required=True)
    consumoMoviles= forms.FloatField(label='Consumo de moviles || en unidades de pertenencia', required=True)
    consumoPortatiles= forms.FloatField(label='Consumo de portatiles || en unidades de pertenencia', required=True)
    consumoCemento= forms.FloatField(label='Consumo de cemento || en unidades de pertenencia', required=True)
    consumoVidrio= forms.FloatField(label='Consumo de vidrio || en unidades de pertenencia', required=True)
    consumoPlastico= forms.FloatField(label='Consumo de plastico || en unidades de pertenencia', required=True)
    consumoAluminio= forms.FloatField(label='Consumo de aluminio || en unidades de pertenencia', required=True)
    consumoTV= forms.FloatField(label='Consumo de TV || en unidades de pertenencia', required=True)
    consumoLavadora= forms.FloatField(label='Consumo de lavadora || en unidades de pertenencia', required=True)
    consumoNevera= forms.FloatField(label='Consumo de nevera || en unidades de pertenencia', required=True)
    consumoMicroondas= forms.FloatField(label='Consumo de secadora || en unidades de pertenencia', required=True)
    consumoOtrosElectronicos= forms.FloatField(label='Consumo de otros electronicos || en unidades de pertenencia', required=True)
    tablaHuella2 = forms.FloatField(label='Id huella tabla 2', required=True)
    consumoMotocicleta= forms.FloatField(label='Consumo de motocicletas || por kilometro recorrido', required=True)
    consumoAutomovilPequeno= forms.FloatField(label='Consumo de coche pequeño || por kilometro recorrido', required=True)   
    consumoAutomovilMediano = forms.FloatField(label='Consumo de coche mediano || por kilometro recorrido', required=True)
    consumoAutomovilGrande = forms.FloatField(label='Consumo de coche grande || por kilometro recorrido', required=True)
    consumoAutomovilDeportivo = forms.FloatField(label='Consumo de coche deportivo || por kilometro recorrido', required=True)
    consumoSUVPequeno = forms.FloatField(label='Consumo de SUV pequeño || por kilometro recorrido', required=True)
    consumoSUVMediano = forms.FloatField(label='Consumo de SUV mediano || por kilometro recorrido', required=True)
    consumoSUVGrande = forms.FloatField(label='Consumo de SUV grande || por kilometro recorrido', required=True)
    consumoSUVDeportivo = forms.FloatField(label='Consumo de SUV deportivo || por kilometro recorrido', required=True)
    consumoAutobus = forms.FloatField(label='Consumo de autobus || por kilometro recorrido', required=True)
    consumoAvion = forms.FloatField(label='Consumo de avion || por kilometro recorrido', required=True)
    consumoBarco = forms.FloatField(label='Consumo de barco || por kilometro recorrido', required=True)
    consumoTren = forms.FloatField(label='Consumo de tren || por kilometro recorrido', required=True)
    consumoAgua = forms.FloatField(label='Consumo de agua || por litros', required=True)
    consumoRes = forms.FloatField(label='Consumo de res || por kilos', required=True)
    consumoCerdo = forms.FloatField(label='Consumo de cerdo || por kilos', required=True)
    consumoPollo = forms.FloatField(label='Consumo de pollo || por kilos', required=True)
    consumoPescado = forms.FloatField(label='Consumo de pescado || por kilos', required=True)
    consumoFrutasYVerduras = forms.FloatField(label='Consumo de frutas y verduras || por kilos', required=True)
    consumoHuevos = forms.FloatField(label='Consumo de huevos || por kilos', required=True)
    consumoLeche = forms.FloatField(label='Consumo de leche || por kilos', required=True)
    consumoQueso = forms.FloatField(label='Consumo de queso || por kilos', required=True)
    consumoCacao = forms.FloatField(label='Consumo de cacao || por kilos', required=True)
    consumoCafe = forms.FloatField(label='Consumo de cafe || por kilos', required=True)
    consumoAzucar = forms.FloatField(label='Consumo de azucar || por kilos', required=True)
    consumoCereal = forms.FloatField(label='Consumo de cereal || por kilos', required=True)
    consumoAceite = forms.FloatField(label='Consumo de aceite || por kilos', required=True)
    consumoBebidasAlcoholicas = forms.FloatField(label='Consumo de bebidas alcoholicas || por litros', required=True)
